[build]
  command = "npm install && cd client && npm install && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://ftcdtxzxrsufgtqfpfre.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_KrGT5IrPl9CfEIVz7VAzZQ_-MW8Qtow"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
